import { SECTION_ORDER_DEFAULT } from './resumeDefaults.js';

// Fictional candidate used for "Load Demo Resume" (spec section 49).
export const DEMO_RESUME = {
  title: 'Software Engineer Resume',
  template: 'software-engineer',
  pageSize: 'A4',
  personal: {
    fullName: 'Jordan Avery',
    title: 'Software Engineer',
    email: 'jordan.avery@example.com',
    phone: '+1 (555) 214-7788',
    location: 'Austin, TX',
    linkedin: 'linkedin.com/in/jordanavery',
    github: 'github.com/jordanavery',
    portfolio: 'jordanavery.dev',
    profileImage: '',
  },
  summary: {
    text: 'Software Engineer with 3+ years building full-stack web applications using React, Node.js, and Java across e-commerce and fintech products. Experienced designing REST APIs, optimizing MongoDB data models, and shipping features to AWS-hosted production environments serving hundreds of thousands of users.',
    yearsOfExperience: '3+',
    industry: 'Software / E-commerce',
    primarySkills: ['React', 'Node.js', 'Java', 'MongoDB', 'AWS'],
    careerGoal: 'Grow into a senior full-stack role owning end-to-end product features.',
  },
  experience: [
    {
      company: 'Northwind Retail Co.',
      role: 'Software Engineer',
      location: 'Austin, TX',
      employmentType: 'Full-time',
      startDate: 'Jun 2022',
      endDate: '',
      current: true,
      description: '',
      technologies: ['React', 'Node.js', 'Express', 'MongoDB', 'AWS', 'Docker'],
      achievements: [
        'Developed and shipped 12+ customer-facing features for a React/Node.js e-commerce platform serving 250K+ monthly active users.',
        'Redesigned the checkout REST API, reducing average response time by consolidating redundant MongoDB queries.',
        'Built a reusable component library adopted across 3 internal product teams, cutting new feature UI development time.',
        'Collaborated with design and product to implement A/B tested onboarding flows, improving signup completion.',
      ],
      order: 0,
    },
    {
      company: 'BrightPath Fintech',
      role: 'Software Engineer Intern',
      location: 'Remote',
      employmentType: 'Internship',
      startDate: 'Jan 2022',
      endDate: 'May 2022',
      current: false,
      description: '',
      technologies: ['Java', 'Spring Boot', 'PostgreSQL', 'JUnit'],
      achievements: [
        'Implemented backend endpoints for a Spring Boot microservice handling transaction categorization.',
        'Wrote unit and integration tests with JUnit, increasing service test coverage.',
        'Partnered with senior engineers to debug and resolve production data inconsistencies.',
      ],
      order: 1,
    },
  ],
  education: [
    {
      degree: 'B.S.',
      field: 'Computer Science',
      university: 'University of Texas at Austin',
      location: 'Austin, TX',
      startDate: 'Aug 2018',
      endDate: 'May 2022',
      gpa: '3.7',
      coursework: ['Data Structures', 'Algorithms', 'Databases', 'Operating Systems'],
      order: 0,
    },
  ],
  skills: [
    { category: 'Languages', items: ['JavaScript', 'TypeScript', 'Java', 'Python', 'SQL'], order: 0 },
    { category: 'Frontend', items: ['React', 'Redux', 'HTML', 'CSS', 'Tailwind CSS'], order: 1 },
    { category: 'Backend', items: ['Node.js', 'Express', 'Spring Boot', 'REST APIs'], order: 2 },
    { category: 'Databases', items: ['MongoDB', 'PostgreSQL', 'MySQL'], order: 3 },
    { category: 'Tools & Cloud', items: ['Git', 'Docker', 'AWS', 'Postman', 'JIRA'], order: 4 },
  ],
  projects: [
    {
      name: 'TaskFlow - Team Task Manager',
      type: 'Full-stack web app',
      description: '',
      technologies: ['React', 'Node.js', 'MongoDB', 'Socket.io'],
      githubUrl: 'github.com/jordanavery/taskflow',
      liveUrl: 'taskflow-demo.dev',
      startDate: 'Mar 2021',
      endDate: 'Aug 2021',
      bullets: [
        'Built a real-time collaborative task board using React and Socket.io supporting live multi-user updates.',
        'Designed a MongoDB schema and REST API for boards, tasks, and team membership with role-based access.',
        'Deployed the application to a cloud environment with CI-based automated deployments.',
      ],
      order: 0,
    },
  ],
  achievements: [
    {
      title: "Dean's List",
      organization: 'University of Texas at Austin',
      date: '2020, 2021',
      description: 'Recognized for academic performance in the top 10% of the Computer Science cohort.',
      order: 0,
    },
  ],
  certifications: [
    { name: 'AWS Certified Cloud Practitioner', issuer: 'Amazon Web Services', date: '2023', credentialUrl: '', order: 0 },
  ],
  languages: [{ name: 'English', proficiency: 'Native', order: 0 }],
  awards: [],
  volunteer: [],
  publications: [],
  links: [{ label: 'Portfolio', url: 'jordanavery.dev', order: 0 }],
  sectionOrder: SECTION_ORDER_DEFAULT,
  sectionVisibility: {},
  latexCode: '',
  atsScore: 0,
  atsAnalysis: null,
  jobDescription: '',
  keywordAnalysis: null,
};

export default DEMO_RESUME;
