export const SECTION_ORDER_DEFAULT = [
  'summary',
  'experience',
  'education',
  'skills',
  'projects',
  'achievements',
  'certifications',
  'languages',
  'awards',
  'volunteer',
  'publications',
  'links',
];

export function emptyResume(overrides = {}) {
  return {
    title: 'Untitled Resume',
    template: 'modern-professional',
    pageSize: 'A4',
    personal: {
      fullName: '',
      title: '',
      email: '',
      phone: '',
      location: '',
      linkedin: '',
      github: '',
      portfolio: '',
      profileImage: '',
      twitter: '',
      leetcode: '',
      stackoverflow: '',
      medium: '',
      behance: '',
      dribbble: '',
    },
    summary: { text: '', yearsOfExperience: '', industry: '', primarySkills: [], careerGoal: '' },
    experience: [],
    education: [],
    skills: [],
    projects: [],
    achievements: [],
    certifications: [],
    languages: [],
    awards: [],
    volunteer: [],
    publications: [],
    links: [],
    sectionOrder: SECTION_ORDER_DEFAULT,
    sectionVisibility: {},
    latexCode: '',
    atsScore: 0,
    atsAnalysis: null,
    jobDescription: '',
    keywordAnalysis: null,
    ...overrides,
  };
}

export default emptyResume;
