import { Sparkles, RefreshCw, Check, X as XIcon } from 'lucide-react';
import Modal from '../ui/Modal.jsx';
import Button from '../ui/Button.jsx';
import Skeleton from '../ui/Skeleton.jsx';

/**
 * Shows an AI-generated suggestion (plain text or a list of bullets) and lets the
 * user Accept, Regenerate, or Discard it - section 13/14/15/16's accept/reject flow.
 */
export function AISuggestionModal({ open, onClose, loading, result, onAccept, onRegenerate, title = 'AI Suggestion' }) {
  const isList = Array.isArray(result);

  return (
    <Modal open={open} onClose={onClose} title={title} className="max-w-xl">
      <div className="flex items-center gap-2 rounded-lg bg-violet-50 px-3 py-2 text-xs font-medium text-violet-700 dark:bg-violet-950/40 dark:text-violet-300">
        <Sparkles className="h-3.5 w-3.5" /> Generated by Claude - review before accepting.
      </div>

      <div className="mt-4 min-h-[100px] rounded-xl border border-slate-200 bg-slate-50 p-4 text-sm text-slate-700 dark:border-slate-800 dark:bg-slate-900/60 dark:text-slate-200">
        {loading && (
          <div className="space-y-2">
            <Skeleton className="h-4 w-full" />
            <Skeleton className="h-4 w-5/6" />
            <Skeleton className="h-4 w-2/3" />
          </div>
        )}
        {!loading && !isList && <p className="whitespace-pre-wrap leading-relaxed">{result}</p>}
        {!loading && isList && (
          <ul className="list-disc space-y-1.5 pl-4">
            {result.map((b, i) => (
              <li key={i}>{b}</li>
            ))}
          </ul>
        )}
      </div>

      <div className="mt-5 flex justify-end gap-2">
        <Button variant="outline" icon={XIcon} onClick={onClose}>
          Discard
        </Button>
        <Button variant="outline" icon={RefreshCw} onClick={onRegenerate} loading={loading}>
          Regenerate
        </Button>
        <Button icon={Check} onClick={onAccept} disabled={loading || !result}>
          Accept
        </Button>
      </div>
    </Modal>
  );
}

export default AISuggestionModal;
