// Converts Resume JSON into LaTeX source using a small, reusable template engine.
// This keeps LaTeX generation decoupled from any single resume (section 23).

function esc(str = '') {
  return String(str)
    .replace(/\\/g, '\\textbackslash{}')
    .replace(/([%&$#_{}])/g, '\\$1')
    .replace(/~/g, '\\textasciitilde{}')
    .replace(/\^/g, '\\textasciicircum{}');
}

function joinNonEmpty(items, sep = ' \\quad | \\quad ') {
  return items.filter(Boolean).map(esc).join(sep);
}

function dateRange(start, end, current) {
  const endLabel = current ? 'Present' : end || '';
  return [start, endLabel].filter(Boolean).join(' -- ');
}

const PREAMBLE = (title) => `% Generated by ResumeForge AI - reusable LaTeX resume template
\\documentclass[10.5pt,letterpaper]{article}
\\usepackage[margin=0.65in]{geometry}
\\usepackage{enumitem}
\\usepackage{titlesec}
\\usepackage{hyperref}
\\usepackage{fontawesome5}
\\pagestyle{empty}
\\setlist[itemize]{leftmargin=*, itemsep=1pt, topsep=2pt}
\\titleformat{\\section}{\\large\\bfseries}{}{0em}{}[\\titlerule]
\\titlespacing{\\section}{0pt}{8pt}{4pt}
\\hypersetup{colorlinks=true, urlcolor=blue}
\\newcommand{\\resumeItem}[1]{\\item{#1}}
\\newcommand{\\resumeHeading}[2]{\\textbf{#1} \\hfill #2}

\\begin{document}
\\begin{center}
  {\\Huge \\bfseries ${esc(title)}}
\\end{center}
`;

const FOOTER = `\\end{document}\n`;

function personalHeader(personal = {}) {
  const contactLine = joinNonEmpty([
    personal.email,
    personal.phone,
    personal.location,
    personal.linkedin,
    personal.github,
    personal.portfolio,
  ]);
  return `\\begin{center}
${esc(personal.title || '')} \\\\
${contactLine}
\\end{center}
`;
}

function summarySection(summary = {}) {
  if (!summary.text) return '';
  return `\\section{Professional Summary}\n${esc(summary.text)}\n`;
}

function experienceSection(items = []) {
  if (!items.length) return '';
  const body = items
    .map((e) => {
      const bullets = (e.achievements?.length ? e.achievements : e.description ? [e.description] : [])
        .map((b) => `  \\resumeItem{${esc(b)}}`)
        .join('\n');
      return `\\resumeHeading{${esc(e.role || '')}, ${esc(e.company || '')}}{${esc(dateRange(e.startDate, e.endDate, e.current))}} \\\\
\\textit{${esc(e.location || '')}}
\\begin{itemize}
${bullets}
\\end{itemize}
`;
    })
    .join('\n');
  return `\\section{Experience}\n${body}`;
}

function educationSection(items = []) {
  if (!items.length) return '';
  const body = items
    .map((e) => `\\resumeHeading{${esc(e.degree || '')} in ${esc(e.field || '')}, ${esc(e.university || '')}}{${esc(dateRange(e.startDate, e.endDate))}} \\\\
${e.gpa ? `GPA: ${esc(e.gpa)}` : ''}
`)
    .join('\n');
  return `\\section{Education}\n${body}`;
}

function skillsSection(items = []) {
  if (!items.length) return '';
  const body = items
    .filter((c) => c.items?.length)
    .map((c) => `\\textbf{${esc(c.category)}:} ${joinNonEmpty(c.items, ', ')} \\\\`)
    .join('\n');
  return `\\section{Skills}\n${body}\n`;
}

function projectsSection(items = []) {
  if (!items.length) return '';
  const body = items
    .map((p) => {
      const bullets = (p.bullets?.length ? p.bullets : p.description ? [p.description] : [])
        .map((b) => `  \\resumeItem{${esc(b)}}`)
        .join('\n');
      const tech = p.technologies?.length ? ` \\textit{(${joinNonEmpty(p.technologies, ', ')})}` : '';
      return `\\resumeHeading{${esc(p.name || '')}}{${esc(dateRange(p.startDate, p.endDate))}}${tech}
\\begin{itemize}
${bullets}
\\end{itemize}
`;
    })
    .join('\n');
  return `\\section{Projects}\n${body}`;
}

function simpleListSection(title, items = [], render) {
  if (!items.length) return '';
  return `\\section{${title}}\n${items.map(render).join('\n')}\n`;
}

export function resumeToLatex(resume) {
  const title = resume.personal?.fullName || resume.title || 'Resume';
  const sectionOrder = resume.sectionOrder?.length
    ? resume.sectionOrder
    : ['summary', 'experience', 'education', 'skills', 'projects', 'achievements', 'certifications'];

  const renderers = {
    summary: () => summarySection(resume.summary),
    experience: () => experienceSection(resume.experience),
    education: () => educationSection(resume.education),
    skills: () => skillsSection(resume.skills),
    projects: () => projectsSection(resume.projects),
    achievements: () =>
      simpleListSection('Achievements', resume.achievements, (a) => `\\textbf{${esc(a.title)}} -- ${esc(a.organization || '')} (${esc(a.date || '')}) \\\\ ${esc(a.description || '')}`),
    certifications: () =>
      simpleListSection('Certifications', resume.certifications, (c) => `\\textbf{${esc(c.name)}} -- ${esc(c.issuer || '')} (${esc(c.date || '')})`),
    languages: () =>
      simpleListSection('Languages', resume.languages, (l) => `${esc(l.name)} -- ${esc(l.proficiency)}`),
    awards: () =>
      simpleListSection('Awards', resume.awards, (a) => `\\textbf{${esc(a.title)}} -- ${esc(a.issuer || '')} (${esc(a.date || '')})`),
    volunteer: () =>
      simpleListSection('Volunteer Experience', resume.volunteer, (v) => `\\textbf{${esc(v.role)}}, ${esc(v.organization)} (${esc(dateRange(v.startDate, v.endDate))}) \\\\ ${esc(v.description || '')}`),
    publications: () =>
      simpleListSection('Publications', resume.publications, (p) => `${esc(p.title)} -- ${esc(p.publisher || '')} (${esc(p.date || '')})`),
    links: () =>
      simpleListSection('Links', resume.links, (l) => `${esc(l.label)}: \\url{${l.url || ''}}`),
  };

  const sections = sectionOrder
    .filter((key) => resume.sectionVisibility?.[key] !== false)
    .map((key) => renderers[key]?.())
    .filter(Boolean)
    .join('\n');

  return `${PREAMBLE(title)}${personalHeader(resume.personal)}\n${sections}\n${FOOTER}`;
}

export default { resumeToLatex };
